services:
  frontend:
    build:
      context: ./client
    container_name: client
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./server
    container_name: server
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata6:/data/db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  dbdata6:
